// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationProduct.MySQLMilkoscan;

namespace MigrationProduct.MySQLMilkoscan.Create
{
    [DbContext(typeof(ConnectionMilkoscan))]
    [Migration("20210323132932_CreateMigration")]
    partial class CreateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("MigrationProduct.Bottling.DoubleComponentsC", b =>
                {
                    b.Property<int>("SampleIndex")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<byte>("IntakeNumerator")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SyntheticNumerator")
                        .HasColumnType("tinyint");

                    b.Property<short>("WorkstationID")
                        .HasColumnType("smallint");

                    b.Property<double?>("ReferenceValue")
                        .HasColumnType("double");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("SampleIndex", "CID", "IntakeNumerator", "SyntheticNumerator", "WorkstationID");

                    b.HasIndex("SampleIndex", "IntakeNumerator", "SyntheticNumerator", "WorkstationID");

                    b.ToTable("doublecomponent");
                });

            modelBuilder.Entity("MigrationProduct.Bottling.ResultsC", b =>
                {
                    b.Property<int>("SampleIndex")
                        .HasColumnType("int");

                    b.Property<byte>("IntakeNumerator")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SyntheticNumerator")
                        .HasColumnType("tinyint");

                    b.Property<short>("WorkstationID")
                        .HasColumnType("smallint");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<bool>("Export")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("InstrumentSampleID")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<short>("IsLinkDiagnosticUploaded")
                        .HasColumnType("smallint");

                    b.Property<short>("IsModified")
                        .HasColumnType("smallint");

                    b.Property<short>("IsMosaicUploaded")
                        .HasColumnType("smallint");

                    b.Property<int>("JobIndex")
                        .HasColumnType("int");

                    b.Property<int>("Numerator")
                        .HasColumnType("int");

                    b.Property<int>("OriginalJobIndex")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("RackID")
                        .HasColumnType("int");

                    b.Property<byte>("ResultSubType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ResultTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("ResultType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SaveForever")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SetupIndex")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<bool>("StoreOnServer")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SampleIndex", "IntakeNumerator", "SyntheticNumerator", "WorkstationID");

                    b.ToTable("result");
                });

            modelBuilder.Entity("MigrationProduct.Bottling.TextComponentsC", b =>
                {
                    b.Property<int>("SampleIndex")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<byte>("IntakeNumerator")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SyntheticNumerator")
                        .HasColumnType("tinyint");

                    b.Property<short>("WorkstationID")
                        .HasColumnType("smallint");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("SampleIndex", "CID", "IntakeNumerator", "SyntheticNumerator", "WorkstationID");

                    b.HasIndex("SampleIndex", "IntakeNumerator", "SyntheticNumerator", "WorkstationID");

                    b.ToTable("textcomponent");
                });

            modelBuilder.Entity("MigrationProduct.Curd.tblMfCdPredictedValueC", b =>
                {
                    b.Property<long>("PredictedValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AggregationType")
                        .HasColumnType("int");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<double?>("DoubleResult")
                        .HasColumnType("double");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OutlierStatus")
                        .HasColumnType("int");

                    b.Property<int>("ParameterLogicalID")
                        .HasColumnType("int");

                    b.Property<int>("ProductLimitsStatus")
                        .HasColumnType("int");

                    b.Property<double?>("RawResult")
                        .HasColumnType("double");

                    b.Property<long>("SubSampleID")
                        .HasColumnType("bigint");

                    b.Property<int>("SystemID")
                        .HasColumnType("int");

                    b.Property<string>("TextResult")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.HasKey("PredictedValueID");

                    b.ToTable("fsprediction");
                });

            modelBuilder.Entity("MigrationProduct.Curd.tblMfCdProductC", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AdvancedInstruments")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AdvancedPredictionModels")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AdvancedProductLimits")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("datetime");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("GUID")
                        .HasColumnType("varbinary(16)");

                    b.Property<int?>("HierarchyFileID")
                        .HasColumnType("int");

                    b.Property<long?>("InstrumentGroupLogicalID")
                        .HasColumnType("bigint");

                    b.Property<int>("InstrumentTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("Latest")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAtUTC")
                        .HasColumnType("datetime");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("NameTranslationID")
                        .HasColumnType("bigint");

                    b.Property<int>("NetworkID")
                        .HasColumnType("int");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PredictionMode")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<int?>("ProductGroupID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductIconID")
                        .HasColumnType("int");

                    b.Property<int>("ProductLogicalID")
                        .HasColumnType("int");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int?>("SampleType")
                        .HasColumnType("int");

                    b.Property<bool>("SpecificSlopeIntercept")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SystemID")
                        .HasColumnType("int");

                    b.Property<bool?>("Valid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("fsproduct");
                });

            modelBuilder.Entity("MigrationProduct.Curd.tblMfCdSampleC", b =>
                {
                    b.Property<long>("SampleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AnalysisEndUTC")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("AnalysisStartUTC")
                        .HasColumnType("datetime");

                    b.Property<int?>("AuditTrailID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAtUTC")
                        .HasColumnType("datetime");

                    b.Property<int>("EventsStatus")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentLogicalID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUTC")
                        .HasColumnType("datetime");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OutlierStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProductLimitsStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProductLogicalID")
                        .HasColumnType("int");

                    b.Property<int>("RawDataStatus")
                        .HasColumnType("int");

                    b.Property<string>("SampleNumber")
                        .HasColumnType("text");

                    b.Property<int>("SampleType")
                        .HasColumnType("int");

                    b.Property<byte[]>("SampleinstrumentID")
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<int?>("SignatureVersion")
                        .HasColumnType("int");

                    b.Property<int>("SystemID")
                        .HasColumnType("int");

                    b.HasKey("SampleID");

                    b.ToTable("fssample");
                });

            modelBuilder.Entity("MigrationProduct.Curd.tblMfCdSubSampleC", b =>
                {
                    b.Property<long>("SubSampleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("EventsStatus")
                        .HasColumnType("int");

                    b.Property<int>("Info")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OutlierStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ParentSubSampleID")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductLimitsStatus")
                        .HasColumnType("int");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("RawDataStatus")
                        .HasColumnType("int");

                    b.Property<long>("SampleID")
                        .HasColumnType("bigint");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubSampleNumber")
                        .HasColumnType("int");

                    b.Property<int>("SystemID")
                        .HasColumnType("int");

                    b.HasKey("SubSampleID");

                    b.ToTable("fssubsample");
                });

            modelBuilder.Entity("MigrationProduct.Intake.PredictionC", b =>
                {
                    b.Property<int>("SampRef")
                        .HasColumnType("int");

                    b.Property<short>("RepNoRef")
                        .HasColumnType("smallint");

                    b.Property<int>("CompRef")
                        .HasColumnType("int");

                    b.Property<short?>("Flags")
                        .HasColumnType("smallint");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("SampRef", "RepNoRef", "CompRef");

                    b.ToTable("prediction");
                });

            modelBuilder.Entity("MigrationProduct.Intake.ProductC", b =>
                {
                    b.Property<int>("ProdNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AllowCheckSampleDefinition")
                        .HasColumnType("tinyint(1)");

                    b.Property<short?>("CleaningIntensity")
                        .HasColumnType("smallint");

                    b.Property<short?>("CleaningTemperature")
                        .HasColumnType("smallint");

                    b.Property<short?>("CurNoOfPilots")
                        .HasColumnType("smallint");

                    b.Property<bool?>("CurVersion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("DilutionFactorIdeal")
                        .HasColumnType("double");

                    b.Property<double?>("DilutionFactorMax")
                        .HasColumnType("double");

                    b.Property<double?>("DilutionFactorMin")
                        .HasColumnType("double");

                    b.Property<bool?>("HideAllGH")
                        .HasColumnType("tinyint(1)");

                    b.Property<short?>("IconNo")
                        .HasColumnType("smallint");

                    b.Property<int?>("IconPos")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<short?>("NoOfCols")
                        .HasColumnType("smallint");

                    b.Property<short?>("NoOfComps")
                        .HasColumnType("smallint");

                    b.Property<int?>("OrigProdRef")
                        .HasColumnType("int");

                    b.Property<short?>("PcaFailMode")
                        .HasColumnType("smallint");

                    b.Property<short?>("PilotMeanMax")
                        .HasColumnType("smallint");

                    b.Property<short?>("PilotMode")
                        .HasColumnType("smallint");

                    b.Property<short?>("PipetteShake")
                        .HasColumnType("smallint");

                    b.Property<bool?>("Preflush")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProdDate")
                        .HasColumnType("text");

                    b.Property<bool?>("Protected")
                        .HasColumnType("tinyint(1)");

                    b.Property<short?>("PumpStrokes")
                        .HasColumnType("smallint");

                    b.Property<short?>("PurgeAlarmTimeout")
                        .HasColumnType("smallint");

                    b.Property<bool?>("ReducedVolume")
                        .HasColumnType("tinyint(1)");

                    b.Property<short?>("Replicates")
                        .HasColumnType("smallint");

                    b.Property<double?>("SampleWeightMax")
                        .HasColumnType("double");

                    b.Property<double?>("SampleWeightMin")
                        .HasColumnType("double");

                    b.Property<double?>("SampleWeightideal")
                        .HasColumnType("double");

                    b.Property<short?>("UsabilityLevel")
                        .HasColumnType("smallint");

                    b.Property<bool?>("UseDilution")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<short?>("Viscosity")
                        .HasColumnType("smallint");

                    b.HasKey("ProdNo");

                    b.ToTable("product");
                });

            modelBuilder.Entity("MigrationProduct.Intake.SampleC", b =>
                {
                    b.Property<int>("SampNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<double>("DilutionFactor")
                        .HasColumnType("double");

                    b.Property<bool>("Excluded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint");

                    b.Property<short>("NoOfReps")
                        .HasColumnType("smallint");

                    b.Property<int>("ProdRef")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .HasColumnType("text");

                    b.Property<double>("SampleWeight")
                        .HasColumnType("double");

                    b.Property<string>("UDF1")
                        .HasColumnType("text");

                    b.Property<string>("UDF2")
                        .HasColumnType("text");

                    b.Property<string>("UDF3")
                        .HasColumnType("text");

                    b.Property<string>("UDF4")
                        .HasColumnType("text");

                    b.Property<int>("ZeroRef")
                        .HasColumnType("int");

                    b.HasKey("SampNo");

                    b.ToTable("sample");
                });

            modelBuilder.Entity("MigrationProduct.Bottling.DoubleComponentsC", b =>
                {
                    b.HasOne("MigrationProduct.Bottling.ResultsC", "Results")
                        .WithMany("DoubleComponents")
                        .HasForeignKey("SampleIndex", "IntakeNumerator", "SyntheticNumerator", "WorkstationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Results");
                });

            modelBuilder.Entity("MigrationProduct.Bottling.TextComponentsC", b =>
                {
                    b.HasOne("MigrationProduct.Bottling.ResultsC", "Results")
                        .WithMany("TextComponents")
                        .HasForeignKey("SampleIndex", "IntakeNumerator", "SyntheticNumerator", "WorkstationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Results");
                });

            modelBuilder.Entity("MigrationProduct.Bottling.ResultsC", b =>
                {
                    b.Navigation("DoubleComponents");

                    b.Navigation("TextComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
